# Generated by Django 5.2.14 on 2026-05-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_rename_expiration_date_announcement_event_date'),
        ('accounts', '0050_add_user_consent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
