# Generated by Django 5.2.14 on 2026-07-26 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0113_add_component_fields_for_mapeh'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('grade_level', models.CharField(max_length=20)),
                ('quarter', models.IntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3')], null=True)),
                ('semester', models.IntegerField(blank=True, choices=[(1, '1st Semester'), (2, '2nd Semester')], null=True)),
                ('strand', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('plan_type', models.CharField(choices=[('dlp', 'Daily Lesson Plan (DLP)'), ('dll', 'Daily Lesson Log (DLL)')], default='dlp', max_length=5)),
                ('date', models.DateField()),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3')])),
                ('week', models.IntegerField(blank=True, null=True)),
                ('objectives', models.TextField(help_text='IPI - Intention, Purpose, Importance')),
                ('content', models.TextField(help_text='Content/Topic')),
                ('materials_needed', models.TextField(blank=True, default='')),
                ('procedure', models.JSONField(blank=True, default=list, help_text='Structured steps: [{step, description, time_minutes}]')),
                ('values_integration', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('revision_needed', 'Revision Needed')], default='draft', max_length=20)),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('identification', 'Identification'), ('essay', 'Essay'), ('true_false', 'True or False'), ('fill_blank', 'Fill in the Blank')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('conceptual', 'Conceptual Understanding'), ('procedural', 'Procedural Fluency'), ('application', 'Application'), ('analysis', 'Analysis'), ('evaluation', 'Evaluation'), ('other', 'Other')], default='other', max_length=20)),
                ('content', models.TextField(help_text='The question text')),
                ('points', models.IntegerField(default=1)),
                ('options', models.JSONField(blank=True, default=list, help_text='JSON array of options for MC/TF questions')),
                ('correct_answer', models.CharField(blank=True, help_text='Correct answer for identification/fill-blank', max_length=500)),
                ('model_answer', models.TextField(blank=True, help_text='Model answer or rubric for essay questions')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False, help_text='Visible to all teachers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=15)),
                ('time_limit_minutes', models.IntegerField(blank=True, help_text='Null = no time limit', null=True)),
                ('max_attempts', models.IntegerField(default=1, help_text='Number of allowed attempts')),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('show_correct_answers', models.BooleanField(default=True, help_text='Show correct answers after submission')),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('grade_component', models.CharField(blank=True, choices=[('', 'Not linked'), ('written_work', 'Written Work'), ('performance_task', 'Performance Task'), ('quarterly_assessment', 'Quarterly Assessment')], default='', max_length=30)),
                ('total_points', models.IntegerField(default=0)),
                ('question_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, help_text='Student answer (string or array)', null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_graded', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Display name (e.g. '1st Term')", max_length=100)),
                ('semester_type', models.CharField(choices=[('1st', 'First Semester'), ('2nd', 'Second Semester'), ('summer', 'Summer'), ('1st Quarter', 'First Quarter'), ('2nd Quarter', 'Second Quarter'), ('3rd Quarter', 'Third Quarter'), ('4th Quarter', 'Fourth Quarter'), ('1st Term', 'First Term'), ('2nd Term', 'Second Term'), ('3rd Term', 'Third Term')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-academic_year__start_date', 'semester_type'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3')])),
                ('goals', models.TextField(help_text='Weekly goals')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='to_user',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='idx_announce_status_audience_time',
        ),
        migrations.RemoveIndex(
            model_name='announcementcomment',
            name='idx_announce_comment_time',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='idx_assign_class_due',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='idx_attend_student_date',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='idx_attend_class_date',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='idx_attend_schedule_date',
        ),
        migrations.RemoveIndex(
            model_name='behavioralrecord',
            name='idx_behavior_student_date',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='idx_chatmsg_room_time_sender',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='idx_grade_class_qtr_year',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='idx_grade_student_qtr_year',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='idx_grade_subj_qtr_class',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_notif_recipient_time',
        ),
        migrations.RemoveIndex(
            model_name='otp',
            name='idx_otp_user_time',
        ),
        migrations.RemoveIndex(
            model_name='studentclassenrollment',
            name='idx_enrollment_student',
        ),
        migrations.RemoveIndex(
            model_name='studentclassenrollment',
            name='idx_enrollment_classroom',
        ),
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='accounts_ap_timesta_094fcf_idx',
            old_name='accounts_ap_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='accounts_ap_endpoin_f4b171_idx',
            old_name='accounts_ap_endpoint_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='accounts_ap_user_id_6e1355_idx',
            old_name='accounts_ap_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_user_id_d4cccd_idx',
            old_name='accounts_au_user_id_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_action_11cc52_idx',
            old_name='accounts_au_action_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_model_n_67e677_idx',
            old_name='accounts_au_model_timestamp_idx',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.OneToOneField(blank=True, help_text='The advisory teacher for this classroom. Each teacher can only have one advisory classroom.', limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classroom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('grade', 'Grade Update'), ('attendance', 'Attendance'), ('fee', 'Fee Reminder'), ('message', 'Message'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='accounts_user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='accounts_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='curriculumstandard',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_standards', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='accounts.classroom'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='curriculum_standards',
            field=models.ManyToManyField(blank=True, related_name='lesson_plans', to='accounts.curriculumstandard'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='submitted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_lesson_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.questionbank'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='accounts.classroom'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='accounts.question'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='accounts.quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='accounts.question'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='accounts.quiz'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='accounts.academicyear'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='accounts.classroom'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='lesson_plans',
            field=models.ManyToManyField(blank=True, related_name='weekly_plans', to='accounts.lessonplan'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('quiz', 'student', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'semester_type')},
        ),
    ]
