# Generated by Django 5.2.14 on 2026-08-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_rename_current_quarter_to_current_term'),
        ('accounts', '0119_enrollment_audit_improvements'),
        ('accounts', '0129_chatroom_group_type'),
    ]

    operations = [
    ]
