# Generated by Django 5.2.14 on 2026-08-01 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0130_merge_20260801_2144'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValuesGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.CharField(choices=[('makadiyos', 'Maka-Diyos'), ('makatao', 'Makatao'), ('makakalikasan', 'Makakalikasan'), ('makabansa', 'Makabansa')], max_length=20)),
                ('rating', models.IntegerField(choices=[(4, 'Advanced (4)'), (3, 'Proficient (3)'), (2, 'Approaching Proficiency (2)'), (1, 'Developing (1)')])),
                ('quarter', models.IntegerField(help_text='Quarter (1-4)')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-quarter', 'value_type'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='to_user',
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-academic_year__start_date', 'semester_type']},
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='idx_announce_status_audience_time',
        ),
        migrations.RemoveIndex(
            model_name='announcementcomment',
            name='idx_announce_comment_time',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='idx_assign_class_due',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='idx_attend_student_date',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='idx_attend_class_date',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='idx_attend_schedule_date',
        ),
        migrations.RemoveIndex(
            model_name='behavioralrecord',
            name='idx_behavior_student_date',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='idx_chatmsg_room_time_sender',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='idx_grade_class_qtr_year',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='idx_grade_student_qtr_year',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='idx_grade_subj_qtr_class',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_notif_recipient_time',
        ),
        migrations.RemoveIndex(
            model_name='otp',
            name='idx_otp_user_time',
        ),
        migrations.RemoveIndex(
            model_name='studentclassenrollment',
            name='idx_enrollment_student',
        ),
        migrations.RemoveIndex(
            model_name='studentclassenrollment',
            name='idx_enrollment_classroom',
        ),
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='accounts_ap_timesta_094fcf_idx',
            old_name='accounts_ap_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='accounts_ap_endpoin_f4b171_idx',
            old_name='accounts_ap_endpoint_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='accounts_ap_user_id_6e1355_idx',
            old_name='accounts_ap_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_user_id_d4cccd_idx',
            old_name='accounts_au_user_id_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_action_11cc52_idx',
            old_name='accounts_au_action_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_model_n_67e677_idx',
            old_name='accounts_au_model_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollmentapplication',
            new_name='accounts_en_lrn_84f03c_idx',
            old_name='accounts_en_lrn_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollmentapplication',
            new_name='accounts_en_email_7bad4b_idx',
            old_name='accounts_en_email_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollmentapplication',
            new_name='accounts_en_enrollm_6cfa58_idx',
            old_name='accounts_en_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollmentapplication',
            new_name='accounts_en_school__9fa33f_idx',
            old_name='accounts_en_sy_status_idx',
        ),
        migrations.RenameIndex(
            model_name='integritylog',
            new_name='accounts_in_attempt_abcc06_idx',
            old_name='accounts_in_attempt_type_idx',
        ),
        migrations.RenameIndex(
            model_name='integritylog',
            new_name='accounts_in_attempt_f4024b_idx',
            old_name='accounts_in_attempt_time_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='accounts_qu_bank_id_c1bfe0_idx',
            old_name='accounts_qu_bank_type_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='accounts_qu_created_400e1d_idx',
            old_name='accounts_qu_created_active_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='accounts_qu_questio_7b14db_idx',
            old_name='accounts_qu_type_diff_idx',
        ),
        migrations.RenameIndex(
            model_name='questionbank',
            new_name='accounts_qu_subject_9c90cc_idx',
            old_name='accounts_qu_subject_idx',
        ),
        migrations.RenameIndex(
            model_name='questionbank',
            new_name='accounts_qu_created_f0fe09_idx',
            old_name='accounts_qu_created_idx',
        ),
        migrations.RenameIndex(
            model_name='questionbank',
            new_name='accounts_qu_is_shar_bc70db_idx',
            old_name='accounts_qu_is_shared_idx',
        ),
        migrations.RenameIndex(
            model_name='quiz',
            new_name='accounts_qu_classro_493bb2_idx',
            old_name='accounts_qu_class_status_idx',
        ),
        migrations.RenameIndex(
            model_name='quiz',
            new_name='accounts_qu_subject_70f8d3_idx',
            old_name='accounts_qu_subj_status_idx',
        ),
        migrations.RenameIndex(
            model_name='quiz',
            new_name='accounts_qu_created_486028_idx',
            old_name='accounts_qu_created_status_idx',
        ),
        migrations.RenameIndex(
            model_name='quiz',
            new_name='accounts_qu_status_cd4bbd_idx',
            old_name='accounts_qu_status_dates_idx',
        ),
        migrations.RenameIndex(
            model_name='quizanswer',
            new_name='accounts_qu_attempt_153314_idx',
            old_name='accounts_qu_attempt_question_idx',
        ),
        migrations.RenameIndex(
            model_name='quizattempt',
            new_name='accounts_qu_quiz_id_55cc6b_idx',
            old_name='accounts_qu_quiz_student_sub_idx',
        ),
        migrations.RenameIndex(
            model_name='quizattempt',
            new_name='accounts_qu_student_fa17ea_idx',
            old_name='accounts_qu_student_sub_idx',
        ),
        migrations.RenameIndex(
            model_name='quizattempt',
            new_name='accounts_qu_quiz_id_565e09_idx',
            old_name='accounts_qu_quiz_sub_idx',
        ),
        migrations.RenameIndex(
            model_name='quizquestion',
            new_name='accounts_qu_quiz_id_ad1b86_idx',
            old_name='accounts_qu_quiz_order_idx',
        ),
        migrations.RenameIndex(
            model_name='studentpromotionrecord',
            new_name='accounts_st_student_98511c_idx',
            old_name='accounts_st_student_sy_idx',
        ),
        migrations.RenameIndex(
            model_name='studentpromotionrecord',
            new_name='accounts_st_status_6f4056_idx',
            old_name='accounts_st_status_idx',
        ),
        migrations.RenameIndex(
            model_name='studentpromotionrecord',
            new_name='accounts_st_is_fina_74160d_idx',
            old_name='accounts_st_is_final_idx',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='slot_type',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.OneToOneField(blank=True, help_text='The advisory teacher for this classroom. Each teacher can only have one advisory classroom.', limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classroom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='procedure',
            field=models.JSONField(blank=True, default=list, help_text='Structured steps: [{step, description, time_minutes}]'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('grade', 'Grade Update'), ('attendance', 'Attendance'), ('fee', 'Fee Reminder'), ('message', 'Message'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='enrollment_status',
            field=models.CharField(choices=[('active', 'Active'), ('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn'), ('transferred', 'Transferred Out'), ('dropped', 'Dropped'), ('graduated', 'Graduated'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('conceptual', 'Conceptual Understanding'), ('procedural', 'Procedural Fluency'), ('application', 'Application'), ('analysis', 'Analysis'), ('evaluation', 'Evaluation'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Correct answer for identification/fill-blank', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation shown after answering'),
        ),
        migrations.AlterField(
            model_name='question',
            name='model_answer',
            field=models.TextField(blank=True, help_text='Model answer or rubric for essay questions'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of options for MC/TF questions'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('identification', 'Identification'), ('essay', 'Essay'), ('true_false', 'True or False'), ('fill_blank', 'Fill in the Blank')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Tags for categorization e.g. ['algebra','chapter1']"),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Visible to all teachers'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='grade_component',
            field=models.CharField(blank=True, choices=[('', 'Not linked'), ('quiz', 'Quiz'), ('exam', 'Exam'), ('activity', 'Activity'), ('written_work', 'Written Work'), ('performance_task', 'Performance Task'), ('quarterly_assessment', 'Quarterly Assessment')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts',
            field=models.IntegerField(default=1, help_text='Number of allowed attempts'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum percentage to pass (null = no passing score)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='show_correct_answers',
            field=models.BooleanField(default=True, help_text='Show correct answers after submission'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.IntegerField(blank=True, help_text='Null = no time limit', null=True),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='answer',
            field=models.JSONField(blank=True, help_text='Student answer (string or array)', null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(blank=True, help_text="Display name (e.g. '1st Term')", max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='component',
            field=models.CharField(blank=True, choices=[('core', 'Core Subject'), ('mapeh', 'MAPEH Component'), ('guidance', 'Homeroom Guidance')], help_text='Subject component category (core, mapeh, guidance)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='academic_level',
            field=models.CharField(choices=[('jhs', 'Junior High School (Grades 7-10)'), ('shs', 'Senior High School (Grades 11-12)'), ('both', 'Both (JHS + SHS)')], default='jhs', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='accounts_user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='accounts_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='corevaluesgrade',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values_grades', to='accounts.classroom'),
        ),
        migrations.AddField(
            model_name='corevaluesgrade',
            name='graded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_core_values', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corevaluesgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.AlterUniqueTogether(
            name='corevaluesgrade',
            unique_together={('student', 'classroom', 'value_type', 'quarter')},
        ),
    ]
