# Generated by Django 5.2.14 on 2026-08-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0131_merge_enrollment_status_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('pending_requirements', 'Pending Requirements'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('enrolled', 'Enrolled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmentstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('pending_requirements', 'Pending Requirements'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('enrolled', 'Enrolled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentstatushistory',
            name='to_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('pending_requirements', 'Pending Requirements'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('enrolled', 'Enrolled')], max_length=20),
        ),
    ]
