# Generated by Django 5.2.14 on 2026-08-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0133_add_withdrawn_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='slot_type',
            field=models.CharField(choices=[('class', 'Class Period'), ('recess', 'Recess'), ('lunch', 'Lunch Break'), ('vacant', 'Vacant'), ('assembly', 'Assembly'), ('pe', 'PE / Sports')], default='class', help_text='Type of this time slot.', max_length=20),
        ),
    ]
