# Generated by Django 5.2.14 on 2026-08-02 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0107_schedule_subject_nullable'),
        ('accounts', '0135_backfill_timeslot_slot_type'),
    ]

    operations = [
    ]
