# Generated by Django 5.2.14 on 2026-08-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0151_merge_consent_and_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('photo', models.URLField(blank=True, help_text='Supabase Storage URL for photo', max_length=500, null=True)),
                ('category', models.CharField(choices=[('administration', 'Administration'), ('faculty', 'Faculty')], default='faculty', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='to_user',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='ann_pinned_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmember',
            name='member_user_room_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='msg_room_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='msg_sender_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='msg_room_read_sender_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatroom',
            name='room_updated_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='gradereport',
            name='gr_student_cls_qt_sy_idx',
        ),
        migrations.RenameIndex(
            model_name='compliancesubmission',
            new_name='accounts_co_status_0d3b0d_idx',
            old_name='compliance_status_type_idx',
        ),
        migrations.RenameIndex(
            model_name='compliancesubmission',
            new_name='accounts_co_teacher_88ee32_idx',
            old_name='compliance_teacher_status_idx',
        ),
        migrations.RenameIndex(
            model_name='compliancesubmission',
            new_name='accounts_co_academi_8dc647_idx',
            old_name='compliance_year_semester_idx',
        ),
        migrations.RenameIndex(
            model_name='compliancesubmission',
            new_name='accounts_co_classro_35bb0c_idx',
            old_name='idx_compliance_classroom_subject',
        ),
        migrations.AlterField(
            model_name='gradingperiod',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')]),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
