# Generated by Django 5.2.14 on 2026-10-03 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_add_user_consent_fields'),
        ('accounts', '0157_engagement_features'),
        ('accounts', '0157_user_department_fk'),
    ]

    operations = [
    ]
