export const API_ENDPOINTS = {
  auth: {
    login: '/login/',
    logout: '/logout/',
    tokenRefresh: '/token/refresh/',
    changePassword: '/auth/change-password/',
    forcePasswordChange: '/force-password-change/',
    verifyOtp: '/verify-otp/',
    resendOtp: '/resend-otp/',
    profile: '/profile/',
    studentProfile: '/student/profile/',
  },
  users: {
    list: '/users/',
    create: '/admin/create-user/',
    detail: (id: number) => `/users/${id}/`,
  },
  academic: {
    classrooms: '/classrooms/',
    subjects: '/subjects/',
    classroomSubjects: '/classroom-subjects/',
    academicYears: '/admin/academic-years/',
    semesters: '/admin/semesters/',
    settings: '/system/settings/',
  },
  enrollment: {
    applications: '/enrollment-applications/',
    detail: (id: number) => `/enrollment-applications/${id}/`,
    classes: '/enrollments/',
    waitlist: '/enrollment-waitlist/',
    checkResult: '/check-result/',
  },
  grades: {
    grades: '/grades/',
    summary: '/grades/summary/',
    reports: '/grade-reports/',
    distribution: '/admin/grade-distribution/',
    analytics: '/admin/grade-analytics/',
  },
  attendance: {
    attendance: '/attendance/',
    summary: '/attendance/summary/',
    analytics: '/admin/attendance-analytics/',
    excuses: '/absence-excuses/',
  },
  schedule: {
    rooms: '/rooms/',
    timeSlots: '/time-slots/',
    schedules: '/schedules/',
  },
  chat: {
    rooms: '/chat/rooms/',
    messages: '/chat/messages/',
    reports: '/chat/reports/',
  },
  notifications: {
    list: '/notifications/',
    polling: '/notifications/polling/',
    preferences: '/notification-preferences/',
    fcmTokens: '/fcm-tokens/',
  },
  announcements: {
    list: '/announcements/',
    public: '/announcements/public/',
  },
  records: {
    transcripts: '/transcripts/',
    transferCertificates: '/transfer-certificates/',
    characterCertificates: '/character-certificates/',
    achievements: '/achievement-records/',
    requests: '/record-requests/',
  },
  finance: {
    fees: '/fees/',
    scratchCards: '/scratch-cards/',
    pendingFees: '/admin/pending-fees/',
  },
  tickets: {
    list: '/tickets/',
    detail: (id: number) => `/tickets/${id}/`,
    departments: '/department-contacts/',
  },
  dashboard: {
    admin: '/admin/stats/',
    teacher: '/teacher/stats/',
    student: '/student/dashboard/stats/',
    parent: '/parent/dashboard/',
    systemMetrics: '/admin/system-metrics/',
    storageAnalytics: '/admin/storage-analytics/',
  },
  events: {
    schoolEvents: '/school-events/',
    calendar: '/student/calendar/',
  },
  parents: {
    dashboard: '/parent/dashboard/',
    childDetail: (studentId: number) => `/parent/child/${studentId}/`,
    reportCardPdf: (studentId: number) => `/parent/child/${studentId}/report-card-pdf/`,
    yearOverYear: (studentId: number) => `/parent/child/${studentId}/year-over-year/`,
  },
  admin: {
    maintenanceMode: '/admin/maintenance-mode/',
    maintenanceStatus: '/system/maintenance-status/',
    backups: '/admin/backups/',
    runBackup: '/admin/run-backup/',
    auditLogs: '/admin/audit-logs/',
    clearCache: '/admin/clear-cache/',
    forceSync: '/admin/force-sync/',
    dataRetention: '/admin/data-retention/',
  },
  website: {
    content: '/website-content/',
  },
  departments: {
    list: '/departments/',
    staffPerformance: '/staff-performance/',
  },
  ptm: {
    meetings: '/ptm-meetings/',
  },
  behavioral: {
    records: '/behavioral-records/',
  },
} as const;